import { Platform, StyleSheet } from 'react-native';
export const C = {
  bg: '#F8F7F2',
  paper: '#FFFFFF',
  ink: '#263D32',
  muted: '#737E74',
  green: '#2F5140',
  lime: '#E7EECF',
  border: '#E5E8DF',
  peach: '#F5E4D6',
  coral: '#B85D40',
  pale: '#EFF2E9',
  red: '#A33C38',
};
export const serif = Platform.select({ ios: 'Georgia', android: 'serif', default: 'Georgia' });
export const S = StyleSheet.create({
  row: { flexDirection: 'row', alignItems: 'center', gap: 10 },
  between: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 12 },
  stack: { gap: 16 },
  wrap: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 },
  heading: { fontFamily: serif, fontSize: 34, lineHeight: 41, color: C.ink, letterSpacing: -1 },
  title: { fontSize: 19, fontWeight: '600', color: C.ink },
  body: { fontSize: 15, lineHeight: 23, color: C.ink },
  muted: { fontSize: 14, lineHeight: 21, color: C.muted },
  eyebrow: { fontSize: 11, fontWeight: '700', letterSpacing: 1.8, color: C.muted },
  card: {
    backgroundColor: C.paper,
    borderRadius: 22,
    borderWidth: 1,
    borderColor: C.border,
    overflow: 'hidden',
  },
  cardBody: { padding: 20, gap: 12 },
  divider: { height: 1, backgroundColor: C.border },
  field: {
    backgroundColor: C.paper,
    borderColor: C.border,
    borderWidth: 1,
    borderRadius: 12,
    paddingHorizontal: 14,
    paddingVertical: 13,
    fontSize: 15,
    color: C.ink,
    minHeight: 48,
  },
  label: { fontSize: 13, fontWeight: '600', color: C.ink, marginBottom: 7 },
  pill: { paddingHorizontal: 13, paddingVertical: 8, borderRadius: 30, backgroundColor: C.pale },
  pillText: { fontSize: 12, color: C.green, fontWeight: '500' },
  button: {
    minHeight: 47,
    borderRadius: 13,
    backgroundColor: C.green,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 19,
    paddingVertical: 12,
    flexDirection: 'row',
    gap: 8,
  },
  buttonText: { fontSize: 14, fontWeight: '600', color: '#fff' },
  iconButton: {
    width: 42,
    height: 42,
    borderRadius: 21,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: C.paper,
    borderWidth: 1,
    borderColor: C.border,
  },
  error: { padding: 14, backgroundColor: '#FBE9E5', borderRadius: 12 },
  empty: { padding: 30, alignItems: 'center', gap: 12 },
});
